### 🧪 Create product
POST http://localhost:3000/products
Content-Type: application/json
x-api-key: your-api-key

{
  "name": "Smartphone",
  "price": 699,
  "category": "electronics",
  "description": "Latest model with absurd camera bumps"
}

### ❌ Create product (invalid JSON)
POST http://localhost:3000/products
Content-Type: application/json
x-api-key: your-api-key

{notValidJson: true

### ❌ Create product (missing body)
POST http://localhost:3000/products
x-api-key: your-api-key

### ❌ Wrong method
PATCH http://localhost:3000/products
Content-Type: application/json
x-api-key: your-api-key

{
  "name": "Oops",
  "price": 0
}

### ✅ Get products (default scan)
GET http://localhost:3000/products
x-api-key: your-api-key

### ✅ Get products with limit
GET http://localhost:3000/products?limit=1
x-api-key: your-api-key

### ✅ Get products with nextToken (copy from response and paste here)
GET http://localhost:3000/products?limit=1&nextToken=eyJzayI6IjIwMjUtMDMtMjhUMDE6NTY6NTMuMjA0WiMyMTdmNzZiMS0yZjVjLTQyNDItYjFmNi03NjhjOTlhOTZkMTciLCJwayI6InByb2R1Y3QifQ==
x-api-key: your-api-key
