AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Faker REST API

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs22.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        FAKER_TABLE: !Ref ProductsDynamoDbTable
        LOCAL_DDB_ENDPOINT: ""

Resources:

  # Add this new resource
  ApiGatewayCloudWatchLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  # Add this new resource
  ApiGatewayAccountConfig:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchLogsRole.Arn

  RestApi:
    Type: AWS::Serverless::Api
    DependsOn: ApiGatewayAccountConfig
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true
      AccessLogSetting:
        DestinationArn: !GetAtt RestApiLogGroup.Arn
        Format: "$context.requestId - $context.identity.sourceIp - $context.httpMethod $context.resourcePath - $context.status"
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          LoggingLevel: INFO
          MetricsEnabled: true

  RestApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigateway/FakerRestApi-${RestApi}"
      RetentionInDays: 7

  RestApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: RestApiProdStage
    Properties:
      ApiStages:
        - ApiId: !Ref RestApi
          Stage: Prod
      Throttle:
        BurstLimit: 100
        RateLimit: 50

  RestApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Enabled: true

  RestUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref RestApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref RestApiUsagePlan

  GetAllProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/get-all-products.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsDynamoDbTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /products/all
            Method: GET
    Metadata:
      BuildMethod: esbuild

  CreateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/create-product.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsDynamoDbTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /products/create
            Method: POST
    Metadata:
      BuildMethod: esbuild

  GetProductByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/get-product-by-id.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsDynamoDbTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /products/by-id
            Method: GET
    Metadata:
      BuildMethod: esbuild

  ProductsDynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FakerRestApi-ProductsDynamoDbTable-1KL76QRAUCEN
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
