AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Faker REST API

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs22.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        FAKER_TABLE: !Ref ProductsDynamoDbTable
        LOCAL_DDB_ENDPOINT: ""

Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true
      AccessLogSetting:
        DestinationArn: !GetAtt RestApiLogGroup.Arn
        Format: "$context.requestId - $context.identity.sourceIp - $context.httpMethod $context.resourcePath - $context.status"
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          LoggingLevel: INFO
          MetricsEnabled: true

  RestApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigateway/${RestApi}"
      RetentionInDays: 7

  RestApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: RestApiProdStage
    Properties:
      ApiStages:
        - ApiId: !Ref RestApi
          Stage: Prod
      Throttle:
        BurstLimit: 100
        RateLimit: 50

  RestApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Enabled: true

  RestUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref RestApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref RestApiUsagePlan

  GetAllProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/get-all-products.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsDynamoDbTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /products
            Method: GET
    Metadata:
      BuildMethod: esbuild

  GetAllProductsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${GetAllProductsFunction}"
      RetentionInDays: 7

  ProductsDynamoDbTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      # TableName: aws-sam-faker-rest-api-ProductsDynamoDbTable-ABC123XYZ
      PrimaryKey:
        Name: id
        Type: String
